# Generated by Django 2.0.10 on 2019-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='busyness',
            field=models.PositiveSmallIntegerField(choices=[(1, 'full time'), (2, 'part time'), (3, 'project work')], null=True),
        ),
    ]
